"""Add async message generation tracking

Revision ID: 6c88f56ded27
Revises: f36552be84a0
Create Date: 2025-12-14 12:52:19.644842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c88f56ded27'
down_revision: Union[str, None] = 'f36552be84a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('generation_task_id', sa.String(length=200), nullable=True))
    op.add_column('messages', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_messages_generation_task_id'), 'messages', ['generation_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_generation_task_id'), table_name='messages')
    op.drop_column('messages', 'generation_params')
    op.drop_column('messages', 'error_message')
    op.drop_column('messages', 'generation_task_id')
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###
