"""add_document_agents_v2

Revision ID: c566496504d4
Revises: d956007f9d39
Create Date: 2026-01-01 13:47:44.482678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c566496504d4'
down_revision: Union[str, None] = 'd956007f9d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_agent_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('vector_index_status', sa.String(length=20), nullable=True),
    sa.Column('keyword_index_status', sa.String(length=20), nullable=True),
    sa.Column('summary_index_status', sa.String(length=20), nullable=True),
    sa.Column('avg_chunk_size', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_agent_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_agent_metadata_resource_id'), ['resource_id'], unique=True)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_agent_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('relevance_keywords', sa.ARRAY(sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('access_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_accessed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('last_accessed_at')
        batch_op.drop_column('access_count')
        batch_op.drop_column('relevance_keywords')
        batch_op.drop_column('doc_agent_cache')

    with op.batch_alter_table('document_agent_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_agent_metadata_resource_id'))

    op.drop_table('document_agent_metadata')
    # ### end Alembic commands ###
